3 add pagination in explorer
polybase/explorer pull request #29
Opened 2023-01-09 23:00 UTC by prllrp

I think I managed to get the PR right this time, please let me know if it looks good.

As far as the feature,  I went ahead and created my own Pagination component. The default page size is 100  but  that can be easily changed or I can add a drop down for user input.

2023-01-10 13:41 UTC, calummoore commented
You need to fix the lint issues. I'd recommend setting up vscode to fix these issues on save. https://www.digitalocean.com/community/tutorials/workflow-auto-eslinting

2023-01-11 19:16 UTC, calummoore requested changes

2023-01-11 19:17 UTC, calummoore commented
Also every time I scroll down, the list goes to 0, which has the effect of scrolling me back to the top of the page. Either cache the results, or user the cursor approach we talked about.

2023-01-11 19:20 UTC, calummoore commented
Also, can you rebase against main

2023-01-11 20:18 UTC, prllrp commented
> Also every time I scroll down, the list goes to 0, which has the effect of scrolling me back to the top of the page. Either cache the results, or user the cursor approach we talked about.

I was only able to reproduce this once, and then without changing anything it went away. The list should never get set to 0. Please let me know if this persists for you

2023-01-12 00:36 UTC, calummoore commented
Please mark the comments as resolved once you've completed them

2023-01-12 00:38 UTC, calummoore commented
> I was only able to reproduce this once, and then without changing anything it went away. The list should never get set to 0. Please let me know if this persists for you

Yes, I'm still seeing this. This may be because when you change the query (e.g. ` .collection('Collection').limit(page * PAGE_LENGTH)`, the `data` prop becomes null while it's loading.

```js
const query = polybase
    .collection('Collection').limit(page * PAGE_LENGTH)

  const { data, loading, error } = useCollection<CollectionMeta>(
    pk
      ? query.where('publicKey', '==', pk)
      : q
```

2023-01-12 00:42 UTC, prllrp commented
> 

Ok I'll implement the cursor tomorrow then, should fix that up.

2023-01-12 09:54 UTC, calummoore commented
> > 
> 
> Ok I'll implement the cursor tomorrow then, should fix that up.

Yeah, or you can implement a cache in the pagination that when it receives null it doesn't update the value:

```js
const ref = useRef([])
if (items) {
  ref.current = items
}
```

2023-01-13 14:40 UTC, calummoore commented on src/features/collections/CollectionList.tsx
> +    pageLength:PAGE_LENGTH,
Can you add an eslint rule for this

2023-01-13 17:34 UTC, calummoore approved these changes

2023-01-13 17:34 UTC, calummoore commented
Please can you rebase against main, and then I will merge. 👍

2023-01-13 17:35 UTC, calummoore commented
And can you please add pagination to the CollectionListData view too

2023-01-13 19:43 UTC, prllrp commented
> And can you please add pagination to the CollectionListData view too

Just to clarify, you mean on the table when you view a collection right? I saw there was an infinite scroll component on the table. Should I look into that?

2023-01-18 17:27 UTC, merged

2023-01-19 00:04 UTC, calummoore commented
Please don't merge these in yourself, I'm not sure why it let you do that.